import type { Product } from "./types";

export const CATEGORIES: string[] = [
  "Hammasi",
  "Ichimliklar",
  "Shirinliklar",
  "Mevalar",
  "Sabzavotlar",
  "Sut mahsulotlari",
  "Non mahsulotlari",
  "Gigiyena",
];

export const PRODUCTS: Product[] = [
  {
    id: "monster-nitro",
    name: "Monster Energy Nitro",
    category: "Ichimliklar",
    emoji: "🥤",
    price: 30000,
    unit: "500 ml",
    description:
      "Monster Energy Nitro — kuchli energiya beruvchi ichimlik. Sport va faol hayot tarzi uchun ideal tanlov.",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "coca-cola",
    name: "Coca-Cola",
    category: "Ichimliklar",
    emoji: "🧋",
    price: 15000,
    oldPrice: 18000,
    unit: "1.5 L",
    description: "Klassik Coca-Cola gazlangan ichimligi. Sovuq holda iste'mol qilish tavsiya etiladi.",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "fuse-tea",
    name: "Fuse Tea limon",
    category: "Ichimliklar",
    emoji: "🧃",
    price: 12000,
    unit: "1 L",
    description: "Limon ta'mli sovuq choy. Tabiiy choy ekstrakti asosida tayyorlangan.",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "alpen-gold",
    name: "Alpen Gold shokolad",
    category: "Shirinliklar",
    emoji: "🍫",
    price: 25000,
    unit: "90 g",
    description: "Sutli shokolad Alpen Gold. Yong'oq va mayiz qo'shilgan mazali plitka.",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "snickers",
    name: "Snickers",
    category: "Shirinliklar",
    emoji: "🍬",
    price: 12000,
    oldPrice: 14000,
    unit: "50 g",
    description: "Yeryong'oq, karamel va nugatli shokolad batonchigi.",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "medovik",
    name: "Medovik tort",
    category: "Shirinliklar",
    emoji: "🍰",
    price: 85000,
    unit: "1 kg",
    description: "Asal qatlamli klassik Medovik torti. Har kuni yangi tayyorlanadi.",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "olma",
    name: "Olma (qizil)",
    category: "Mevalar",
    emoji: "🍎",
    price: 18000,
    unit: "1 kg",
    description: "Shirin va sersuv qizil olma. Mahalliy fermer xo'jaliklaridan yetkazilgan.",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "banan",
    name: "Banan",
    category: "Mevalar",
    emoji: "🍌",
    price: 28000,
    oldPrice: 32000,
    unit: "1 kg",
    description: "Pishgan shirin banan. Vitamin va energiya manbai.",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "apelsin",
    name: "Apelsin",
    category: "Mevalar",
    emoji: "🍊",
    price: 32000,
    unit: "1 kg",
    description: "Sersuv apelsin — C vitaminiga boy sitrus mevasi.",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "uzum",
    name: "Uzum (husayni)",
    category: "Mevalar",
    emoji: "🍇",
    price: 35000,
    unit: "1 kg",
    description: "Husayni navli mahalliy uzum. Shirin va xushbo'y.",
    rating: 4.8,
    inStock: false,
  },
  {
    id: "pomidor",
    name: "Pomidor",
    category: "Sabzavotlar",
    emoji: "🍅",
    price: 14000,
    unit: "1 kg",
    description: "Yangi uzilgan qizil pomidor. Salat va taomlar uchun.",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "bodring",
    name: "Bodring",
    category: "Sabzavotlar",
    emoji: "🥒",
    price: 10000,
    unit: "1 kg",
    description: "Yangi va xushbo'y bodring. Issiqxonada yetishtirilgan.",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "kartoshka",
    name: "Kartoshka",
    category: "Sabzavotlar",
    emoji: "🥔",
    price: 8000,
    unit: "1 kg",
    description: "Sifatli mahalliy kartoshka. Har qanday taom uchun mos.",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "sut",
    name: "Sut",
    category: "Sut mahsulotlari",
    emoji: "🥛",
    price: 14000,
    unit: "1 L",
    description: "Pasterizatsiya qilingan tabiiy sigir suti, 3.2% yog'lilik.",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "qatiq",
    name: "Qatiq",
    category: "Sut mahsulotlari",
    emoji: "🍶",
    price: 9000,
    unit: "500 ml",
    description: "Uy sharoitida tayyorlangan tabiiy qatiq.",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "pishloq",
    name: "Pishloq (gollandcha)",
    category: "Sut mahsulotlari",
    emoji: "🧀",
    price: 45000,
    oldPrice: 52000,
    unit: "400 g",
    description: "Gollandcha pishloq — buterbrod va salatlar uchun ideal.",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "non",
    name: "Buxanka non",
    category: "Non mahsulotlari",
    emoji: "🍞",
    price: 6000,
    unit: "1 dona",
    description: "Yumshoq oq buxanka non. Har kuni yangi yopiladi.",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "patir",
    name: "Patir non",
    category: "Non mahsulotlari",
    emoji: "🫓",
    price: 8000,
    unit: "1 dona",
    description: "Tandirda yopilgan an'anaviy patir non.",
    rating: 4.9,
    inStock: true,
  },
  {
    id: "kruassan",
    name: "Kruassan (shokoladli)",
    category: "Non mahsulotlari",
    emoji: "🥐",
    price: 15000,
    unit: "1 dona",
    description: "Shokolad qo'shilgan yumshoq fransuz kruassani.",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "colgate",
    name: "Colgate tish pastasi",
    category: "Gigiyena",
    emoji: "🪥",
    price: 24000,
    unit: "100 ml",
    description: "Colgate Total tish pastasi — 12 soatlik himoya.",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "fairy",
    name: "Fairy idish yuvish",
    category: "Gigiyena",
    emoji: "🧴",
    price: 19000,
    oldPrice: 22000,
    unit: "450 ml",
    description: "Fairy idish yuvish vositasi — limon xushbo'yligi bilan.",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "safeguard",
    name: "Safeguard sovun",
    category: "Gigiyena",
    emoji: "🧼",
    price: 9000,
    unit: "90 g",
    description: "Antibakterial Safeguard sovuni butun oila uchun.",
    rating: 4.4,
    inStock: true,
  },
];

/** Format a UZS amount with thin spaces: 30000 -> "30 000 UZS" */
export function formatUZS(amount: number): string {
  const formatted = Math.round(amount)
    .toString()
    .replace(/\B(?=(\d{3})+(?!\d))/g, " ");
  return `${formatted} UZS`;
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
